# Timing consistency
- ros_topic_name: 'clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

# Odometry (if available)
- ros_topic_name: 'odometry'
  gz_topic_name: '/model/drone/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'ignition.msgs.Odometry'
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: 'imu'
  gz_topic_name: '/model/drone/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'ignition.msgs.IMU'
  direction: GZ_TO_ROS

# Command velocity
- ros_topic_name: 'cmd_vel'
  gz_topic_name: '/model/drone/cmd_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_type_name: 'ignition.msgs.Twist'
  direction: ROS_TO_GZ

  #IR CAMERA
- ros_topic_name: "ir_camera/image_raw"
  gz_topic_name: "/model/drone/ir_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS


